<?php require('template/header.phtml') ?>
<body id="mainbody">
    <h2>Welcome to the Borrow My Charger Website!</h2></br>
    <?php if (!isset($_SESSION["login"])) :?> <!-- if not logged in show log in fields-->
         <h2>Please login or register</h2></br>
            <form method="post" action="" >
                <?php if (!isset($_GET['wrongDetails'])) :?>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="email" class="form-control" placeholder="Enter your Email" name="username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" placeholder="Enter your Password" name="password">
                    </div>
                <?php else: ?>
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="email" class="form-control is-invalid" placeholder="Enter your Email" name="username">
                        <div class="invalid-feedback" id="search-student">
                            Wrong username
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control is-invalid" placeholder="Enter your Password" name="password">
                        <div class="invalid-feedback" id="search-student">
                            Wrong password
                        </div>
                    </div>
                <?php endif;?>
                <div class="form-group">
                    <input type="submit" class=" btn btn-primary" id="loginbtn" name="loginbutton" value="Login">
                </div>
                <input type="submit" class=" btn btn-primary" id="registerbtn" name="registerbutton" value="Register" ">
            </form>




    <?php else : ?> <!-- if logged in show logged in-->
        <h2>You are logged in</h2></br>
    <?php endif;?>
    <script src="../js/traffic.js"></script>
</body>
<?php require('template/footer.phtml') ?>
