<?php require('template/header.phtml') ?>
<head>
    <link rel="stylesheet" href="../leaflet/leaflet.css" />
    <script src="../leaflet/leaflet.js"></script>
    <script src="../js/maping.js" defer></script>

</head>

<body>
    <div class="container-fluid">
            <div id="popup">

                    <div class="card-body">
                        <h2>List Search</h2>
                    </div>

                <div class="container" id="search">
                    <div class="input-group">
                        <div class="dropdown">
                            <button class="btn btn-outline-secondary dropdown-toggle"
                                    type="button" id="dropdownMenuButton">Options</button>
                            <div class="dropdown-menu" id="searchOption">
                                <a href="#" class="dropdown-item" id="option1" data-value = "address">Address</a>
                                <a href="#" class="dropdown-item" id="option2" data-value = "postCode">PostCode</a>
                                <a href="#" class="dropdown-item" id="option3" data-value = "cost">Price</a>
                            </div>
                        </div>
                        <input type="text" id="searchField"class="form-control" placeholder="Search">
                    </div>
                </div>
                <div id="searchResultsContainer" class="scrollable-container"></div>
            </div>
            <div id="contact-message">
                <div class="card">
                    <div class="card-body">
                        <button id="closeBtn" type="button" class="btn-close" aria-label="Close"></button>
                        <h3 class="mb-3">Contact Owner</h3>
                        <!-- Owner's Profile picture-->
                        <div class="mb-3">
                            <img src="" alt="" id="contact-profile-picture" >
                        </div>

                        <!-- Owner's Name -->
                        <p class="mb-3">Owner's Name: <span id="ownerName"></span></p>
                        <!-- Owner's Email -->
                        <p class="mb-3">Owner's Email: <span id="ownerEmail"></span></p>
                        <!-- Message Input -->
                        <div class="mb-3">
                            <label for="message" class="form-label">Message:</label>
                            <input type="text" class="form-control" id="message" placeholder="Type your message here">
                        </div>
                        <!-- Date and Time Picker -->
                        <div class="mb-3">
                            <label for="dateTime" class="form-label">Date and Time:</label>
                            <input type="datetime-local" class="form-control" id="dateTime">
                        </div>
                        <!-- Send Button -->
                        <div class="d-grid">
                            <div id="send-message-button-popup" class="btn btn-primary" tabindex="0">Send Message</div>
                        </div>

                    </div>
                </div>
            </div>
            <div id="map" class="map-container"></div>

        <script  type="text/javascript" >

            var map = L.map('map').setView([51.505, -0.09], 13);

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
                maxZoom: 18,
            }).addTo(map);
        </script>
    </div>
</body>
<?php require('template/footer.phtml') ?>
