<?php require('template/header.phtml') ?>
<head>
    <link rel="stylesheet" href="../leaflet/leaflet.css" />
    <script src="../leaflet/leaflet.js"></script>
    <script src="../js/maping.js" defer></script>

</head>

<body>
    <div class="container-fluid">
        <div id="map" ></div>
        <script  type="text/javascript" >
            var map = L.map('map').setView([51.505, -0.09], 13);

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
                maxZoom: 18,
            }).addTo(map);
        </script>
    </div>




</body>
<?php require('template/footer.phtml') ?>
