<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="../../css/my-style.css" rel="stylesheet">

    <title> Borrow my charger - <?php echo $view->pageTitle; ?></title>
</head>


<!--<body class="d-flex flex-column h-100">-->




    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="index.php">BMC</a>`
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">


                    <?php

                    if (!isset($_SESSION["login"])) {
                        echo '';
                    }
                    else
                    {
                        echo '
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        
                        <li class="nav-item">
                            <a href="myAccount.php" class="nav-link">My Account</a>
                        </li>
                        <li class="nav-item">
                            <a href="chargerInfo.php" class="nav-link">Find A Charger</a>
                        </li>
                        

                    </ul>
                        <form method="post" action="" class="form text-primary">
                            <input type="submit"class=" btn btn-success" id="logoutbtn" name="logoutbutton" value="Logout">
                        </form>';
                    }
                    ?>


                </div>
            </div>
        </nav>
    </header>


    <!-- Begin page content -->
    <main class="flex-shrink-0">

        <div class="container">
            <div  class="row">
                <div id="title" class="col-xs-12">

                    <h1><?php echo $view->pageTitle ?> </h1>

                    <!-- https://getbootstrap.com/docs/5.2/examples/sticky-footer-navbar/ -->

                </div>
            </div>

            <div class="row">
               <section id="content" class="col-xs-6 col-sm-9 col-md-10">



